### ISSUE TITLE
FCC corrupted database

### ISSUE THREAD

**Issue by TheHexorcist** [johnstonbl01/clementinejs#53]
I have a corrupted database (mongodb) using the clementinejs.  I need to know how to reset it or how to pull this database out of the "node_modules" folder.  I see this becoming a huge problem for future FCC peps.  when I do a git from the server with last known good configuration I still have a corrupted db.  I think this is because of the ".gitignore" file.

**Comment by johnstonbl01** [comment]
The DB exists independent of the application and is stored on disk. However, I think we can fix this.

Try this:

(If you're using c9, make sure you have `mongod --smallfiles` running in a separate terminal window -- if you're developing locally, then the mongod service should already be running)

`mongo`

This connects to the mongodb instance.

`show dbs`

You should see the DB in question listed.

`use <dbname-here>`

This command makes the `<dbname-here>` the active db.

`db.dropDatabase()`

`show dbs`

The DB should no longer be listed. Let me know if you run into any issues.

**Comment by TheHexorcist** [comment]
It turns out it was something i changed in the "ajax-functions.js" file to cause the error.  It is very confusing to me to not see the database stored somewhere?  I'm using C9.

**Comment by johnstonbl01** [comment]
The database is stored in c9's memory.

If you install it locally, it gets installed to your disk. It's the same thing, except you're using a cloud-based workspace, so the database is stored in the cloud. It isn't connected to the app in any way.

What you'll see most times is that apps will "seed" the database. This process inserts data the first time the app is run. This is done because databases don't travel with the apps are are instead part of the environment in which the app runs. Hope that helps.
