### ISSUE TITLE
Using JQuery in Client side controller (clickController.client.js)

### ISSUE THREAD

**Issue by sachinmour** [johnstonbl01/clementinejs#62]
I started following tutorials for clementinejs through official tutorial and when i got to part where you define methods related to loading files after dom is loaded and making ajax requests, i was a little too overwhelmed because i never had to deal with that before and i always took help from jquery.

So, i completed the tutorial but using jquery instead and i thought if anybody else would like to do so too.

**Comment by johnstonbl01** [comment]
Hi, @sachinmour. While I do understand where you're coming from, it's important to understand the foundation of the jQuery methods. Clementine doesn't include jQuery because the jQuery library is bigger than the entire Clementine application, and as such provides an unwarranted overhead. If you have any specific questions about the vanilla AJAX functions - I'm happy to discuss.

**Comment by sachinmour** [comment]
Thank you @johnstonbl01, I understand the problem. I already took the time to understand all the methods you defined in the application and i wouldn't have understood them better if it wasn't for your application. jQuery was just a suggestion maybe we can add jquery in comments in the code.
